import React from "react";
import type { Metadata } from "next";
import Navbar from "@/components/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
    children: React.ReactNode;
};


export default async function RootLayout({ children }: RootLayoutProps) {

    return (
        <>
            <Navbar/>
            <section className="py-4">
                <div className="container mx-auto">
                    {children}
                </div>
            </section>
        </>
    );
}
